apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wso2is-mysql-volume
  labels:
    type: local
    app: wso2is-mysql
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/wso2is-mysql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wso2is-mysql-claim
  namespace: wso2
  labels:
    app: wso2is-mysql
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  volumeName: pv-wso2is-mysql-volume
